// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHA8f6629Wbo3nyauSbcIdeaAPeeGxZ1M',
    appId: '1:437183231180:web:cd8c108348c6afc4f97e69',
    messagingSenderId: '437183231180',
    projectId: 'wms-appi1',
    authDomain: 'wms-appi1.firebaseapp.com',
    storageBucket: 'wms-appi1.firebasestorage.app',
    measurementId: 'G-SYR5ZTB4VF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcDBZSJ7KSBLgUq7f0EeVcvMh0rYdC694',
    appId: '1:437183231180:android:26524c7c226caf66f97e69',
    messagingSenderId: '437183231180',
    projectId: 'wms-appi1',
    storageBucket: 'wms-appi1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt9foPdl5zSLXh76Fo3R0_cAm4sNG3TOE',
    appId: '1:437183231180:ios:2757af2cb342b587f97e69',
    messagingSenderId: '437183231180',
    projectId: 'wms-appi1',
    storageBucket: 'wms-appi1.firebasestorage.app',
    iosBundleId: 'com.example.wmsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt9foPdl5zSLXh76Fo3R0_cAm4sNG3TOE',
    appId: '1:437183231180:ios:2757af2cb342b587f97e69',
    messagingSenderId: '437183231180',
    projectId: 'wms-appi1',
    storageBucket: 'wms-appi1.firebasestorage.app',
    iosBundleId: 'com.example.wmsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHA8f6629Wbo3nyauSbcIdeaAPeeGxZ1M',
    appId: '1:437183231180:web:56fb1b2eb978600ef97e69',
    messagingSenderId: '437183231180',
    projectId: 'wms-appi1',
    authDomain: 'wms-appi1.firebaseapp.com',
    storageBucket: 'wms-appi1.firebasestorage.app',
    measurementId: 'G-SQMT5KWVPJ',
  );

}